languague: php

sudo: false

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit